pipeline {
  agent any //master, slave 구성 일단 없기에 any
  
  tools { 
      maven 'Maven 3.3.9' 
      jdk 'jdk8' 
  }


  parameters { // 젠킨스 파이프라인 구동시에 넘겨받는 argument
    booleanParam(name : 'BUILD_DOCKER_IMAGE', defaultValue : true, description : 'BUILD_DOCKER_IMAGE')
    booleanParam(name : 'RUN_TEST', defaultValue : true, description : 'RUN_TEST')
    booleanParam(name : 'PUSH_DOCKER_IMAGE', defaultValue : true, description : 'PUSH_DOCKER_IMAGE')
    
  }

  environment { // 전체 스테이지에서 접근가능한 환경변수
    REGION = "ap-northeast-2"
  }

  stages {
    
   stage ('Initialize') {
      steps {
          sh '''
              echo "PATH = ${PATH}"
              echo "M2_HOME = ${M2_HOME}"
          ''' 
      }
   }
    
   stage('============ Build Java ============') { 
        steps { 
           echo 'This is a minimal pipeline.' 
        }
    }
  
    stage('============ Build Docker Image ============') {
        when { 
            expression { return params.BUILD_DOCKER_IMAGE } 
        }
       
        steps {
          dir("${env.WORKSPACE}/chanyApp/deploy") { 
            sh 'ls'
            sh 'docker build -t test:1 .'
          }

            echo "Stage Build"
            echo "성공성공"
        }
        post {
            always {
                echo " Docker Build Success "
            }
        }
    }
    
    
  }
}
